"use client";

import { useState } from "react";
import { jsPDF } from "jspdf";
import { Loader2 } from "lucide-react";

export default function PanMerger() {
  const [frontImage, setFrontImage] = useState(null);
  const [backImage, setBackImage] = useState(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [resultUrl, setResultUrl] = useState(null);

  const handleImageUpload = (file, side) => {
    if (!file || !file.type.startsWith("image/")) {
      alert("Please upload a valid image file (JPG or PNG).");
      return;
    }
    const url = URL.createObjectURL(file);
    if (side === "front") setFrontImage({ file, url });
    else setBackImage({ file, url });
    setResultUrl(null); // Reset result if they change images
  };

  const generatePDF = async () => {
    if (!frontImage || !backImage) return;
    setIsProcessing(true);

    try {
      // Create A4 PDF
      const doc = new jsPDF({ format: "a4", unit: "mm" });
      const pageWidth = 210; // A4 width in mm
      
      // Target dimensions for ID cards (standard ID is approx 85.6mm x 54mm)
      // We will make them slightly larger for clear printing (e.g., 90mm wide)
      const targetWidth = 90;
      const targetHeight = 60;
      
      // Center horizontally
      const xPos = (pageWidth - targetWidth) / 2;
      
      // Position vertically (Front near top, Back in middle)
      const yPosFront = 40;
      const yPosBack = 120;

      // Helper to convert object URL to base64 for jsPDF
      const getBase64 = async (url) => {
        const response = await fetch(url);
        const blob = await response.blob();
        return new Promise((resolve) => {
          const reader = new FileReader();
          reader.onloadend = () => resolve(reader.result);
          reader.readAsDataURL(blob);
        });
      };

      const frontB64 = await getBase64(frontImage.url);
      const backB64 = await getBase64(backImage.url);

      // Add a nice border and title
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("PAN Card (Front & Back)", pageWidth / 2, 25, { align: "center" });
      
      // Add Front
      doc.setDrawColor(200, 200, 200);
      doc.rect(xPos, yPosFront, targetWidth, targetHeight);
      doc.addImage(frontB64, "JPEG", xPos, yPosFront, targetWidth, targetHeight);
      
      // Add Back
      doc.rect(xPos, yPosBack, targetWidth, targetHeight);
      doc.addImage(backB64, "JPEG", xPos, yPosBack, targetWidth, targetHeight);

      // Add footer
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(150, 150, 150);
      doc.text("Generated by DesiPDF", pageWidth / 2, 280, { align: "center" });

      const pdfBlob = doc.output("blob");
      setResultUrl(URL.createObjectURL(pdfBlob));

    } catch (error) {
      console.error(error);
      alert("Error generating PDF. Please try different images.");
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <div className="bg-white dark:bg-[#09090b] rounded-3xl shadow-[0_8px_30px_rgb(0,0,0,0.04)] dark:shadow-none border border-gray-100 dark:border-gray-800 p-6 md:p-10 w-full max-w-4xl mx-auto transition-colors duration-300">
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
        {/* Front Upload */}
        <div className="flex flex-col gap-3">
          <label className="text-sm font-bold text-gray-700 dark:text-gray-300 uppercase tracking-wide flex items-center gap-2">
            <div className="w-6 h-6 rounded-full bg-indigo-100 dark:bg-indigo-900/50 text-indigo-600 dark:text-indigo-400 flex items-center justify-center text-xs">1</div>
            Upload Front Side
          </label>
          {!frontImage ? (
            <div 
              className="border-2 border-dashed border-gray-300 dark:border-gray-700 hover:border-indigo-500 bg-gray-50 dark:bg-gray-900 hover:bg-indigo-50 dark:hover:bg-indigo-900/20 rounded-2xl p-8 text-center cursor-pointer transition h-48 flex flex-col items-center justify-center"
              onDragOver={(e) => e.preventDefault()}
              onDrop={(e) => { e.preventDefault(); handleImageUpload(e.dataTransfer.files[0], 'front'); }}
              onClick={() => document.getElementById("front-upload").click()}
            >
              <i className="fa-regular fa-id-card text-4xl text-indigo-400 mb-3"></i>
              <p className="font-bold text-gray-700 dark:text-gray-300">Click to upload Front</p>
              <input type="file" id="front-upload" accept="image/*" className="hidden" onChange={(e) => handleImageUpload(e.target.files[0], 'front')} />
            </div>
          ) : (
            <div className="relative rounded-2xl overflow-hidden border-2 border-indigo-500 h-48 group">
              <img src={frontImage.url} alt="Front" className="w-full h-full object-cover" />
              <div className="absolute inset-0 bg-black/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition">
                <button onClick={() => {setFrontImage(null); setResultUrl(null);}} className="bg-red-500 text-white px-4 py-2 rounded-lg font-bold hover:bg-red-600 transition">Remove</button>
              </div>
            </div>
          )}
        </div>

        {/* Back Upload */}
        <div className="flex flex-col gap-3">
          <label className="text-sm font-bold text-gray-700 dark:text-gray-300 uppercase tracking-wide flex items-center gap-2">
            <div className="w-6 h-6 rounded-full bg-indigo-100 dark:bg-indigo-900/50 text-indigo-600 dark:text-indigo-400 flex items-center justify-center text-xs">2</div>
            Upload Back Side
          </label>
          {!backImage ? (
            <div 
              className="border-2 border-dashed border-gray-300 dark:border-gray-700 hover:border-indigo-500 bg-gray-50 dark:bg-gray-900 hover:bg-indigo-50 dark:hover:bg-indigo-900/20 rounded-2xl p-8 text-center cursor-pointer transition h-48 flex flex-col items-center justify-center"
              onDragOver={(e) => e.preventDefault()}
              onDrop={(e) => { e.preventDefault(); handleImageUpload(e.dataTransfer.files[0], 'back'); }}
              onClick={() => document.getElementById("back-upload").click()}
            >
              <i className="fa-solid fa-id-card-clip text-4xl text-indigo-400 mb-3"></i>
              <p className="font-bold text-gray-700 dark:text-gray-300">Click to upload Back</p>
              <input type="file" id="back-upload" accept="image/*" className="hidden" onChange={(e) => handleImageUpload(e.target.files[0], 'back')} />
            </div>
          ) : (
            <div className="relative rounded-2xl overflow-hidden border-2 border-indigo-500 h-48 group">
              <img src={backImage.url} alt="Back" className="w-full h-full object-cover" />
              <div className="absolute inset-0 bg-black/50 flex items-center justify-center opacity-0 group-hover:opacity-100 transition">
                <button onClick={() => {setBackImage(null); setResultUrl(null);}} className="bg-red-500 text-white px-4 py-2 rounded-lg font-bold hover:bg-red-600 transition">Remove</button>
              </div>
            </div>
          )}
        </div>
      </div>

      {!resultUrl ? (
        <div className="flex justify-center border-t border-gray-100 dark:border-gray-800 pt-8">
          <button 
            onClick={generatePDF}
            disabled={!frontImage || !backImage || isProcessing}
            className="w-full md:w-auto bg-gradient-to-r from-indigo-600 to-blue-600 hover:from-indigo-700 hover:to-blue-700 disabled:from-gray-300 disabled:to-gray-400 disabled:text-gray-500 text-white px-10 py-4 rounded-xl font-extrabold text-lg flex items-center justify-center gap-3 transition-all shadow-[0_8px_30px_rgba(79,70,229,0.3)] disabled:shadow-none hover:-translate-y-1"
          >
            {isProcessing ? <Loader2 className="animate-spin h-5 w-5" /> : <i className="fa-solid fa-file-pdf text-xl"></i>}
            {isProcessing ? "Creating PDF..." : "Generate A4 Print PDF"}
          </button>
        </div>
      ) : (
        <div className="border-t border-gray-100 dark:border-gray-800 pt-8 text-center animate-in fade-in zoom-in duration-300">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-emerald-100 dark:bg-emerald-900/30 text-emerald-500 rounded-full mb-4">
            <i className="fa-solid fa-check text-3xl"></i>
          </div>
          <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-6">Your Print-Ready PDF is Generated!</h3>
          
          <div className="flex flex-col sm:flex-row justify-center gap-4">
            <button onClick={() => setResultUrl(null)} className="px-6 py-3 bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-xl font-bold transition">
              Make Another
            </button>
            <a href={resultUrl} download="PAN_Aadhaar_A4.pdf" className="px-8 py-3 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl font-bold transition flex items-center justify-center gap-2 shadow-lg shadow-indigo-500/30">
              <i className="fa-solid fa-download"></i> Download A4 PDF
            </a>
          </div>
        </div>
      )}

    </div>
  );
}
